### ISSUE TITLE
when i try to open this close really quickly 

### ISSUE THREAD

**Issue by YagaGameplaysYT** [PsychoPast/LawinServer#2]

**Comment by YagaGameplaysYT** [comment]
A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [C:\Users\USER~1\AppData\Local\Temp\.net\LawinServer (1)\5vyyafkr.tgt\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64

**Comment by PsychoPast** [comment]
Yo. It's self explanatory. You have to download the runtime : https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.7-windows-x64-installer
