### ISSUE TITLE
Kinda Ruined My Pc 

### ISSUE THREAD

**Issue by EgyptianGamer06** [PsychoPast/LawinServer#3]
Hey there !

So i was using this for Polaris and it was working fine 

Then now when i have to use the Internet , i have to open the program

Now every time I open the program it gives me an error after connecting to port 9999

I can't open epic games launcher and this maybe broke my connection for the Pc , any solution ? Plz

**Comment by PsychoPast** [comment]
Hey
Kindly watch
https://cdn.discordapp.com/attachments/719627052596330548/729372299517755452/2020-07-05_17-19-25.mp4
to fix your internet issues
Also please send a screenshot of the console when it errors out

**Comment by EgyptianGamer06** [comment]
Thanks for the help !

now it's working fine with no problems 

after i restarted the PC the error doesn't come out , so i'm sorry i can't get a screenshot for the error 

but Thanks so much for the help !
